/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.czjvic.runmyscript;

import org.openide.util.NbPreferences;

final class RunMyScriptPanel extends javax.swing.JPanel {

    private final RunMyScriptOptionsPanelController controller;

    RunMyScriptPanel(RunMyScriptOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFieldPath = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFieldEnviroment = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        chbFieldParseXml = new javax.swing.JCheckBox();
        chbFieldShowWindow = new javax.swing.JCheckBox();

        txtFieldPath.setText(org.openide.util.NbBundle.getMessage(RunMyScriptPanel.class, "RunMyScriptPanel.text")); // NOI18N
        txtFieldPath.setName(""); // NOI18N
        txtFieldPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldPathActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(RunMyScriptPanel.class, "RunMyScriptPanel.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(RunMyScriptPanel.class, "RunMyScriptPanel.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(RunMyScriptPanel.class, "RunMyScriptPanel.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(RunMyScriptPanel.class, "RunMyScriptPanel.jLabel4.text")); // NOI18N

        txtFieldEnviroment.setText(org.openide.util.NbBundle.getMessage(RunMyScriptPanel.class, "RunMyScriptPanel.txtFieldEnviroment.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(RunMyScriptPanel.class, "RunMyScriptPanel.jLabel5.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(RunMyScriptPanel.class, "RunMyScriptPanel.jLabel6.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, org.openide.util.NbBundle.getMessage(RunMyScriptPanel.class, "RunMyScriptPanel.jLabel7.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(chbFieldParseXml, org.openide.util.NbBundle.getMessage(RunMyScriptPanel.class, "RunMyScriptPanel.chbFieldParseXml.text")); // NOI18N
        chbFieldParseXml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbFieldParseXmlActionPerformed(evt);
            }
        });

        chbFieldShowWindow.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(chbFieldShowWindow, org.openide.util.NbBundle.getMessage(RunMyScriptPanel.class, "RunMyScriptPanel.chbFieldShowWindow.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFieldPath, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldEnviroment)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbFieldShowWindow)
                            .addComponent(chbFieldParseXml))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFieldEnviroment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbFieldShowWindow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chbFieldParseXml)
                .addContainerGap(101, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldPathActionPerformed

    private void chbFieldParseXmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbFieldParseXmlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbFieldParseXmlActionPerformed

    void load() {
        txtFieldPath.setText(NbPreferences.forModule(RunMyScriptPanel.class).get("path", ""));
        txtFieldEnviroment.setText(NbPreferences.forModule(RunMyScriptPanel.class).get("enviroment", ""));
        chbFieldParseXml.setSelected(NbPreferences.forModule(RunMyScriptPanel.class).getBoolean("parseXml", false));
        chbFieldShowWindow.setSelected(NbPreferences.forModule(RunMyScriptPanel.class).getBoolean("showWindow", true));
    }

    void store() {
        NbPreferences.forModule(RunMyScriptPanel.class).put("path", txtFieldPath.getText());
        NbPreferences.forModule(RunMyScriptPanel.class).put("enviroment", txtFieldEnviroment.getText());
        NbPreferences.forModule(RunMyScriptPanel.class).putBoolean("parseXml", chbFieldParseXml.isSelected());
        NbPreferences.forModule(RunMyScriptPanel.class).putBoolean("showWindow", chbFieldShowWindow.isSelected());
    }

    boolean valid() {
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chbFieldParseXml;
    private javax.swing.JCheckBox chbFieldShowWindow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtFieldEnviroment;
    private javax.swing.JTextField txtFieldPath;
    // End of variables declaration//GEN-END:variables
}
